### ISSUE TITLE
Link to Github Profile

### ISSUE THREAD

**Issue by ChristopherDavenport** [Cllezark/hello-world#1]
I made an issue for you to get practice making new branches merging and linking to issues. 

Can you add a link to your github profile from your README.md

Here is [My Profile](https://github.com/ChristopherDavenport)

**Comment by Cllezark** [comment]
Hey Chris!
Thank you for doing that! I'll get right to adding that link.

**Comment by ChristopherDavenport** [comment]
You are looking for using special keywords in your PR into master to automatically close this issue.

[How to close issues via PR](https://github.com/blog/1506-closing-issues-via-pull-requests)
